In [1]:
import numpy as np

lst = [[1, 2, 3],
       [4, 5, 6]]
ary2d = np.array(lst)

int32_arr = ary2d.astype(np.int32)
int32_arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [2]:
np.ones((3, 4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [3]:
np.eye(4, dtype=np.int32) # identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [9]:
a = np.arange(4, 10)
b = np.eye(4, dtype=np.int32)
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [5]:
np.arange(1., 11., 0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9])

In [12]:
b[:, 0]

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0]], dtype=int32)

In [13]:
b[:, :2]

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0]], dtype=int32)

In [14]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape((2,3))
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr_2d.reshape(-1)
arr_2d.flatten() # to flatten an array without copy
arr_2d.ravel() # to flatten an array with copy

array([1, 2, 3, 4, 5, 6])