In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [4]:
np.ndim(A) # return the number of dimensions of array

1

In [5]:
A.shape # A 는 1차원 배열이고 4개의 원소를 가지고 있음 (return tuple type)

(4,)

In [7]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)
print(np.ndim(B))
B.shape

[[1 2]
 [3 4]
 [5 6]]
2


(3, 2)

In [8]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

np.dot(A, B)

array([[19, 22],
       [43, 50]])