<a href="https://colab.research.google.com/github/tmdgusya/ai-study-repository/blob/main/pytorch_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
data = [
    [1,2],
    [3,4,]
]

x = torch.tensor(data)
print(x.is_cuda)

x = x.cuda()
print(x.is_cuda)

x = x.cpu()
print(x.is_cuda)

False
True
False


## 텐서의 속성
- 모양(shape)
- 자료형(data type)
- 저장된 장치

In [5]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [6]:
a = torch.tensor([5])
b = torch.tensor([7])

c = (a + b).numpy()
print(c)
print(type(c))

result = 10 * c
tensor = torch.from_numpy(result)
print(tensor)
print(type(tensor))

[12]
<class 'numpy.ndarray'>
tensor([120])
<class 'torch.Tensor'>


## 텐서 값이 모두 1이 되도록 초기화 가능( 같은 크기를 가지면서)


In [7]:
x = torch.tensor([
    [1,2],
    [3,4],
])

x_ones = torch.ones_like(x)
print(x_ones)

# x 와 같은 크기지만 값은 float 을 채우고, 랜덤으로 채우기
x_rand = torch.rand_like(x, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.5866, 0.5652],
        [0.6584, 0.3141]])


In [3]:
tensor = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
])

print(tensor[0])
print(tensor[:, 0]) # first column (모든 행에 대한 0열의 데이터) = 1,5,9
print(tensor[..., -1]) # last column ('')

tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])


# concatenate tensor

In [5]:
tensor = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
])

t1 = torch.cat([tensor, tensor, tensor], dim=1) # 열기반으로 옆으로 잇는거 즉 N*M 일때 M은 안변함
print(t1)

t2 = torch.cat([tensor, tensor, tensor], dim=0) # 행기반으로 아래로 잇는거 즉 N*M 일때 N은 안변함
print(t2)

tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


# type casting

In [6]:
a = torch.tensor([2], dtype=torch.int32)
print(a.dtype)

b = a.to(dtype=torch.float32)
print(b.dtype)

torch.int32
torch.float32


# change shape of tensor

In [11]:
a = torch.tensor([1,2,3,4,5,6,7,8])
b= a.view(4,2)
print(b)

a[0]= 7
print(b)

b = a.clone().view(4,2)
print(b)

a[0]= 100
print(b)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


# get mean of tensor

In [16]:
a = torch.Tensor([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

a.cuda()

print(a)
print(a.mean())
print(a.mean(dim=0)) # mean for each column
print(a.mean(dim=1)) # mean for each row

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor(5.5000)
tensor([3.5000, 4.5000, 5.5000, 6.5000, 7.5000])
tensor([3., 8.])


# 차원 축소 / 늘리기

In [23]:
a =torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])

a.cuda()

_a = a.unsqueeze(0) # 2*4 행렬일때 첫번에 추가 [1,2,4]
print(_a)
print(_a.shape)
print("==================================")
b = a.unsqueeze(2) # 2*4 행렬일때 3번째에 추가 [2,4,1]
print(b)
print(b.shape)
print("==================================")
c = a.unsqueeze(-1) # 2*4 행렬일때 제일 마지막번째(3)에 추가 [2,4,1]
print(c)
print(c.shape)

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([1, 2, 4])
tensor([[[1.],
         [2.],
         [3.],
         [4.]],

        [[5.],
         [6.],
         [7.],
         [8.]]])
torch.Size([2, 4, 1])
tensor([[[1.],
         [2.],
         [3.],
         [4.]],

        [[5.],
         [6.],
         [7.],
         [8.]]])
torch.Size([2, 4, 1])


In [24]:
d = c.squeeze()
print(d)
print(d.shape)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])
