<a href="https://colab.research.google.com/github/tmdgusya/ai-study-repository/blob/main/pytorch_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
data = [
    [1,2],
    [3,4,]
]

x = torch.tensor(data)
print(x.is_cuda)

x = x.cuda()
print(x.is_cuda)

x = x.cpu()
print(x.is_cuda)

False
True
False


## 텐서의 속성
- 모양(shape)
- 자료형(data type)
- 저장된 장치

In [5]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [6]:
a = torch.tensor([5])
b = torch.tensor([7])

c = (a + b).numpy()
print(c)
print(type(c))

result = 10 * c
tensor = torch.from_numpy(result)
print(tensor)
print(type(tensor))

[12]
<class 'numpy.ndarray'>
tensor([120])
<class 'torch.Tensor'>


## 텐서 값이 모두 1이 되도록 초기화 가능( 같은 크기를 가지면서)


In [7]:
x = torch.tensor([
    [1,2],
    [3,4],
])

x_ones = torch.ones_like(x)
print(x_ones)

# x 와 같은 크기지만 값은 float 을 채우고, 랜덤으로 채우기
x_rand = torch.rand_like(x, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.5866, 0.5652],
        [0.6584, 0.3141]])
